# Generated by Django 6.0.4 on 2026-05-01 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Dịch vụ y tế',
                'verbose_name_plural': 'Dịch vụ y tế',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên thuốc')),
                ('unit', models.CharField(help_text='Viên, Hộp, Chai...', max_length=50, verbose_name='Đơn vị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('usage_instruction', models.TextField(blank=True, null=True, verbose_name='Hướng dẫn sử dụng')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên chuyên khoa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialties/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Chuyên khoa',
                'verbose_name_plural': 'Chuyên khoa',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='Phí khám')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core_clinic.specialty', verbose_name='Chuyên khoa')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Ngày khám')),
                ('time_slot', models.CharField(help_text='VD: 08:00-08:30', max_length=20, verbose_name='Khung giờ')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do khám')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core_clinic.doctor', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Triệu chứng')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Lời dặn dò')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core_clinic.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh án',
                'verbose_name_plural': 'Hồ sơ bệnh án',
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Số lô')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn')),
                ('import_date', models.DateField(verbose_name='Ngày nhập')),
                ('expiration_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core_clinic.medicine', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Lô thuốc',
                'verbose_name_plural': 'Lô thuốc',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Tiền sử bệnh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng tiền')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('VNPAY', 'VNPay'), ('MOMO', 'MoMo')], max_length=10, null=True, verbose_name='Phương thức')),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=10, verbose_name='Trạng thái')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core_clinic.appointment', verbose_name='Lịch hẹn')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core_clinic.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core_clinic.patient', verbose_name='Bệnh nhân'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='core_clinic.medicalrecord', verbose_name='Bệnh án')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('dosage_instruction', models.TextField(verbose_name='Hướng dẫn sử dụng')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_clinic.medicinebatch', verbose_name='Lô thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core_clinic.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
            },
        ),
        migrations.CreateModel(
            name='RecordService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='test_results/', verbose_name='File kết quả')),
                ('status', models.CharField(choices=[('WAITING', 'Chờ kết quả'), ('DONE', 'Đã có kết quả')], default='WAITING', max_length=10, verbose_name='Trạng thái')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core_clinic.medicalrecord', verbose_name='Bệnh án')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_clinic.medicalservice', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Chỉ định dịch vụ',
                'verbose_name_plural': 'Chỉ định dịch vụ',
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'time_slot')},
        ),
    ]
