# Generated by Django 6.0.4 on 2026-05-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinic', '0002_medicalservice_medicine_specialty_doctor_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
    ]
