# Generated by Django 6.0.4 on 2026-05-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinic', '0003_remove_doctor_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='years_of_experience',
        ),
    ]
