# Generated by Django 6.0.4 on 2026-05-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinic', '0004_remove_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do hủy lịch'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Lời dặn dặn'),
        ),
    ]
