import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f5f7fa', padding: 12 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f7fa' },
    mainRevenueCard: { backgroundColor: '#005b9f', borderRadius: 12, elevation: 4, marginBottom: 15 },
    cardLabelMain: { color: '#e3f2fd', fontSize: 13, fontWeight: '600', letterSpacing: 0.5, textAlign: 'center', marginTop: 10 },
    cardValueMain: { color: '#fff', fontSize: 24, fontWeight: 'bold', textAlign: 'center', marginVertical: 10 },
    mainDivider: { backgroundColor: '#b3e5fc', opacity: 0.4, marginVertical: 10 },
    regionRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, marginBottom: 4 },
    regionLabel: { color: '#fff', fontSize: 14 },
    regionValue: { color: '#fff', fontSize: 14, fontWeight: '700' },
    progress: { height: 6, borderRadius: 3, marginBottom: 10 },
    sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#455a64', marginTop: 15, marginBottom: 8, letterSpacing: 0.3 },
    listCard: { backgroundColor: '#fff', borderRadius: 10, elevation: 2 },
    rankBadge: { alignSelf: 'center', backgroundColor: '#ffebee', color: '#c62828', fontSize: 12, fontWeight: 'bold', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    subCard: { backgroundColor: '#fff', borderRadius: 10, elevation: 2, marginBottom: 12 },
    subCardTitle: { fontSize: 15, fontWeight: 'bold', color: '#263238' },
    dataRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: '#eceff1' },
    dataLabel: { fontSize: 14, color: '#37474f' },
    dataValue: { fontSize: 14, fontWeight: '600', color: '#005b9f' },
    titleHead: { fontSize: 14, fontWeight: 'bold', color: '#546e7a', marginBottom: 12, letterSpacing: 0.5, textAlign: 'center' },
    card: { backgroundColor: '#fff', borderRadius: 10, marginBottom: 12, elevation: 2 },
    rowJustify: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 4 },
    invoiceId: { fontSize: 15, fontWeight: 'bold', color: '#263238' },
    label: { fontSize: 13, color: '#78909c', marginTop: 6 },
    valueName: { fontSize: 15, fontWeight: '600', color: '#37474f', marginBottom: 6 },
    priceValue: { fontSize: 16, fontWeight: 'bold', color: '#005b9f' },
    emptyText: { textAlign: 'center', marginTop: 40, color: '#90a4ae' },
    rowAlign: { flexDirection: 'row', alignItems: 'center' },
    patientName: { fontSize: 16, fontWeight: 'bold', color: '#263238' },
    dateText: { fontSize: 12, color: '#78909c' },
    subLabel: { fontSize: 12, color: '#78909c', marginTop: 4 },
    subValue: { fontSize: 14, color: '#37474f', marginBottom: 4, fontWeight: '500' },
    doctorText: { fontSize: 15, fontWeight: 'bold', color: '#263238', flex: 0.6 },
    infoLine: { fontSize: 13, color: '#455a64', marginVertical: 2 },
    rowSpace: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }
});