import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f5f7fa', padding: 12 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f7fa' },
    headerContainer: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 12, backgroundColor: '#f8f9fa' },
    welcomeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
    greetingText: { fontSize: 14, color: '#6c757d' },
    userNameText: { fontSize: 18, fontWeight: 'bold', color: '#212529' },
    hotlineCard: { backgroundColor: '#005b9f', borderRadius: 12, marginBottom: 24 },
    hotlineContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12 },
    hotlineTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
    hotlineSub: { color: '#e3f2fd', fontSize: 12, marginTop: 2 },
    sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#212529', marginBottom: 12 },
    row: { justifyContent: 'space-between', paddingHorizontal: 16, marginBottom: 12 },
    gridItem: { backgroundColor: '#fff', width: '48%', borderRadius: 12, padding: 16, alignItems: 'center', justifyContent: 'center', elevation: 2 },
    card: { backgroundColor: '#fff', borderRadius: 8, marginBottom: 12, elevation: 1 },
    label: { fontSize: 15, fontWeight: 'bold', color: '#343a40', marginTop: 12, marginBottom: 6 },
    input: { marginBottom: 8, backgroundColor: '#fff' },
    slotsRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 12 },
    slotButton: { width: '48%', backgroundColor: '#f1f3f5', paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginBottom: 10, borderWidth: 1, borderColor: '#e9ecef' },
    selectedSlot: { backgroundColor: '#e3f2fd', borderColor: '#005b9f' },
    selectedSlotText: { color: '#005b9f', fontWeight: 'bold' },
    button: { marginTop: 15, paddingVertical: 4, borderRadius: 8 },
    valueName: { fontSize: 16, fontWeight: 'bold', color: '#263238', marginBottom: 6 },
    subValue: { fontSize: 14, color: '#455a64', marginTop: 2, fontWeight: '500' },
    divider: { marginVertical: 8, backgroundColor: '#eceff1' },
    emptyText: { padding: 15, color: '#90a4ae', textAlign: 'center' },
    titleStyle: { fontWeight: 'bold', color: '#005b9f' },
    totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, padding: 10, backgroundColor: '#e3f2fd', borderRadius: 6 },
    totalLabel: { fontSize: 15, fontWeight: 'bold', color: '#005eff' },
    totalValue: { fontSize: 18, fontWeight: 'bold', color: '#005eff' },
    payBtn: { marginTop: 25, paddingVertical: 4, borderRadius: 8, marginBottom: 30 }
});